default: &default
  timeout: 5000
  encoding: utf8
  host: localhost
  username: op_user
  password: "njP4UKt98wvhQLmL"

development:
  <<: *default
  adapter: mysql2
  database: studio_hackthon_menu

production:
  <<: *default
  adapter: mysql2
  database: studio_hackthon_menu
